import http from "node:http";
import { readFileSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes, timingSafeEqual, scryptSync } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import XLSX from "xlsx";

const ROOT=dirname(fileURLToPath(import.meta.url));
const DATA_DIR=join(ROOT,"data");
mkdirSync(DATA_DIR,{recursive:true});
const db=new DatabaseSync(join(DATA_DIR,"credits.db"));
db.exec(`PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS records(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,department TEXT NOT NULL,student_type TEXT NOT NULL CHECK(student_type IN ('undergraduate','graduate')),credits REAL NOT NULL DEFAULT 0,note TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(name,department,student_type));CREATE INDEX IF NOT EXISTS idx_records_lookup ON records(name,department,student_type);CREATE TABLE IF NOT EXISTS settings(key TEXT PRIMARY KEY,value TEXT NOT NULL);INSERT OR IGNORE INTO settings VALUES('threshold_undergraduate','10');INSERT OR IGNORE INTO settings VALUES('threshold_graduate','10');`);
function ensureColumn(table,name,definition){const cols=db.prepare(`PRAGMA table_info(${table})`).all().map(r=>r.name);if(!cols.includes(name))db.exec(`ALTER TABLE ${table} ADD COLUMN ${name} ${definition}`)}
ensureColumn("records","group_name","TEXT NOT NULL DEFAULT ''");ensureColumn("records","group_contact","TEXT NOT NULL DEFAULT ''");ensureColumn("records","political_status","TEXT NOT NULL DEFAULT ''");ensureColumn("records","league_branch","TEXT NOT NULL DEFAULT ''");ensureColumn("records","phone","TEXT NOT NULL DEFAULT ''");ensureColumn("records","email","TEXT NOT NULL DEFAULT ''");ensureColumn("records","withdrawn","INTEGER NOT NULL DEFAULT 0");ensureColumn("records","withdrawal_note","TEXT NOT NULL DEFAULT ''");ensureColumn("records","source_total","REAL");
db.exec("CREATE TABLE IF NOT EXISTS cohorts(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL UNIQUE,active INTEGER NOT NULL DEFAULT 1,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);INSERT OR IGNORE INTO cohorts(name) VALUES('北京大学2025级团支书培训班');");
ensureColumn("records","cohort_id","INTEGER NOT NULL DEFAULT 1");
db.exec(`CREATE TABLE IF NOT EXISTS courses(id INTEGER PRIMARY KEY AUTOINCREMENT,course_key TEXT NOT NULL UNIQUE,name TEXT NOT NULL,category TEXT NOT NULL CHECK(category IN ('required','elective')),credits REAL NOT NULL CHECK(credits>=0),sort_order INTEGER NOT NULL DEFAULT 0,active INTEGER NOT NULL DEFAULT 1,source_header TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_courses_order ON courses(sort_order);CREATE TABLE IF NOT EXISTS attendance(id INTEGER PRIMARY KEY AUTOINCREMENT,student_id INTEGER NOT NULL REFERENCES records(id) ON DELETE CASCADE,course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,status TEXT NOT NULL CHECK(status IN ('attended','makeup','special')),source_mark TEXT NOT NULL DEFAULT '',credit_override REAL,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(student_id,course_id));CREATE INDEX IF NOT EXISTS idx_attendance_student ON attendance(student_id);CREATE INDEX IF NOT EXISTS idx_attendance_course ON attendance(course_id);PRAGMA foreign_keys=ON;PRAGMA optimize;`);
ensureColumn("attendance","credit_override","REAL");
ensureColumn("courses","cohort_id","INTEGER NOT NULL DEFAULT 1");
db.exec("UPDATE courses SET course_key=cohort_id||':'||course_key WHERE instr(course_key,':')=0;");
db.exec(`CREATE TABLE IF NOT EXISTS cohort_settings(cohort_id INTEGER PRIMARY KEY,threshold_undergraduate REAL NOT NULL DEFAULT 10,threshold_graduate REAL NOT NULL DEFAULT 10,threshold_required REAL NOT NULL DEFAULT 0);CREATE TABLE IF NOT EXISTS admin_accounts(id INTEGER PRIMARY KEY AUTOINCREMENT,username TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('super','org','liaison')),cohort_id INTEGER,group_name TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_admin_scope ON admin_accounts(role,cohort_id,group_name);`);
function passwordHash(password,salt=randomBytes(16).toString("hex")){return `${salt}:${scryptSync(String(password),salt,64).toString("hex")}`}
function passwordMatches(password,stored){const [salt,hex]=String(stored).split(":");if(!salt||!hex)return false;const actual=scryptSync(String(password),salt,64),expected=Buffer.from(hex,"hex");return actual.length===expected.length&&timingSafeEqual(actual,expected)}
function seedSuper(username,password){const row=db.prepare("SELECT id FROM admin_accounts WHERE username=?").get(username);if(row)db.prepare("UPDATE admin_accounts SET role='super',active=1,cohort_id=NULL,group_name='' WHERE id=?").run(row.id);else db.prepare("INSERT INTO admin_accounts(username,password_hash,role) VALUES(?,?,'super')").run(username,passwordHash(password))}
if(process.env.SUPER_ADMIN_1_PASSWORD)seedSuper(process.env.SUPER_ADMIN_1_USERNAME||"pkuzzb",process.env.SUPER_ADMIN_1_PASSWORD);
if(process.env.SUPER_ADMIN_2_PASSWORD)seedSuper(process.env.SUPER_ADMIN_2_USERNAME||"zhangtongwei",process.env.SUPER_ADMIN_2_PASSWORD);
if(!db.prepare("SELECT COUNT(*) AS n FROM admin_accounts WHERE active=1").get().n)throw new Error("尚未配置管理员账号。请设置 SUPER_ADMIN_1_PASSWORD 后重新启动。");
const legacy=Object.fromEntries(db.prepare("SELECT key,value FROM settings").all().map(r=>[r.key,Number(r.value)]));for(const c of db.prepare("SELECT id FROM cohorts").all())db.prepare("INSERT OR IGNORE INTO cohort_settings(cohort_id,threshold_undergraduate,threshold_graduate,threshold_required) VALUES(?,?,?,0)").run(c.id,legacy.threshold_undergraduate??10,legacy.threshold_graduate??10);

const sessions=new Map(),SESSION_MS=12*60*60*1000,secureCookie=process.env.COOKIE_SECURE==="true"?"; Secure":"";
const mime={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"text/javascript; charset=utf-8",".svg":"image/svg+xml",".png":"image/png"};
function json(res,status,value,headers={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store",...headers});res.end(JSON.stringify(value))}
function binary(res,buffer,filename){res.writeHead(200,{"Content-Type":"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet","Content-Disposition":`attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,"Content-Length":buffer.length,"Cache-Control":"no-store"});res.end(buffer)}
async function body(req,limit=14_000_000){const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>limit)throw new Error("请求内容过大");chunks.push(c)}return chunks.length?JSON.parse(Buffer.concat(chunks).toString("utf8")):{} }
function token(req){return(req.headers.cookie||"").split(";").map(v=>v.trim()).find(v=>v.startsWith("pku_admin="))?.slice(10)||""}
function adminSession(req){const t=token(req),session=sessions.get(t);if(!session||session.expires<Date.now()){if(t)sessions.delete(t);return null}return session}
function requireAdmin(req,res){const s=adminSession(req);if(!s){json(res,401,{error:"请先登录管理员后台"});return null}return s}
function requireWrite(req,res){const s=requireAdmin(req,res);if(!s)return null;if(s.user.role==="liaison"){json(res,403,{error:"小组联络员账号只有查看权限"});return null}return s}
function requireSuper(req,res){const s=requireAdmin(req,res);if(!s)return null;if(s.user.role!=="super"){json(res,403,{error:"只有校团委组织部账号可以管理账号与权限"});return null}return s}
function safeEqual(a,b){const aa=Buffer.from(String(a)),bb=Buffer.from(String(b));return aa.length===bb.length&&timingSafeEqual(aa,bb)}
function thresholds(cohortId){return db.prepare("SELECT threshold_undergraduate AS undergraduate,threshold_graduate AS graduate,threshold_required AS required FROM cohort_settings WHERE cohort_id=?").get(cohortId)||{undergraduate:10,graduate:10,required:0}}
function publicUser(u){return{id:u.id,username:u.username,role:u.role,roleName:u.role==="super"?"校团委组织部":u.role==="org"?"校团委组织部骨干":"培训班小组联络员",cohortId:u.cohort_id,groupName:u.group_name,canManageAccounts:u.role==="super",canEdit:u.role!=="liaison"}}
function str(v,max=300){return String(v??"").trim().slice(0,max)}
function validType(v){return v==="undergraduate"||v==="graduate"?v:""}
function cleanStudent(v){const s={name:str(v.name,40),department:str(v.department,80),studentType:validType(v.studentType),groupName:str(v.groupName,40),groupContact:str(v.groupContact,40),politicalStatus:str(v.politicalStatus,40),leagueBranch:str(v.leagueBranch,160),phone:str(v.phone,40),email:str(v.email,120),withdrawn:v.withdrawn?1:0,withdrawalNote:str(v.withdrawalNote,100),sourceTotal:v.sourceTotal===""||v.sourceTotal==null?null:Number(v.sourceTotal),note:str(v.note,300)};if(!s.name||!s.department||!s.studentType)throw new Error("学员姓名、院系和类型不能为空");if(s.sourceTotal!=null&&!Number.isFinite(s.sourceTotal))s.sourceTotal=null;return s}
function cleanCourse(v){const c={id:v.id?Number(v.id):null,key:str(v.courseKey,80),name:str(v.name,120),category:v.category==="elective"?"elective":v.category==="required"?"required":"",credits:Number(v.credits),sortOrder:Number(v.sortOrder||0),active:v.active===false||v.active===0?0:1,sourceHeader:str(v.sourceHeader,160)};if(!c.name||!c.category||!Number.isFinite(c.credits)||c.credits<0||c.credits>1000)throw new Error("课程名称、类型或学分无效");if(!c.key)c.key=c.id?`course_${c.id}`:`manual_${Date.now()}_${randomBytes(3).toString("hex")}`;return c}
const creditExpr=`COALESCE((SELECT SUM(COALESCE(a.credit_override,c.credits)) FROM attendance a JOIN courses c ON c.id=a.course_id WHERE a.student_id=r.id AND c.active=1),0)`;
const requiredExpr=`COALESCE((SELECT SUM(COALESCE(a.credit_override,c.credits)) FROM attendance a JOIN courses c ON c.id=a.course_id WHERE a.student_id=r.id AND c.active=1 AND c.category='required'),0)`;
function studentRows(cohortId,groupName=""){const where=groupName?"r.cohort_id=? AND r.group_name=?":"r.cohort_id=?",args=groupName?[cohortId,groupName]:[cohortId];return db.prepare(`SELECT r.id,r.name,r.department,r.student_type AS studentType,r.group_name AS groupName,r.group_contact AS groupContact,r.political_status AS politicalStatus,r.league_branch AS leagueBranch,r.phone,r.email,r.withdrawn,r.withdrawal_note AS withdrawalNote,r.source_total AS sourceTotal,r.note,r.updated_at AS updatedAt,${creditExpr} AS totalCredits,${requiredExpr} AS requiredCredits,(SELECT COUNT(*) FROM attendance a WHERE a.student_id=r.id) AS courseCount FROM records r WHERE ${where} ORDER BY r.student_type,r.group_name,r.department,r.name`).all(...args)}
function courseRows(cohortId){return db.prepare("SELECT id,course_key AS courseKey,name,category,credits,sort_order AS sortOrder,active,source_header AS sourceHeader,updated_at AS updatedAt FROM courses WHERE cohort_id=? ORDER BY sort_order,id").all(cohortId)}
function dashboard(session){const cohortId=session.cohortId,t=thresholds(cohortId),group=session.user.role==="liaison"?session.user.group_name:"",all=studentRows(cohortId,group).map(r=>({...r,completed:!r.withdrawn&&r.totalCredits>=t[r.studentType]&&r.requiredCredits>=t.required})),active=all.filter(r=>!r.withdrawn),cohort=db.prepare("SELECT id,name FROM cohorts WHERE id=?").get(cohortId);const summarize=rows=>{const passed=rows.filter(r=>r.completed).length;return{count:rows.length,passed,rate:rows.length?Math.round(passed*1000/rows.length)/10:0,average:rows.length?Math.round(rows.reduce((s,r)=>s+r.totalCredits,0)*10/rows.length)/10:0}};return{cohort,user:publicUser(session.user),records:all,courses:courseRows(cohortId),thresholds:t,stats:{total:summarize(active),undergraduate:summarize(active.filter(r=>r.studentType==="undergraduate")),graduate:summarize(active.filter(r=>r.studentType==="graduate")),withdrawn:all.length-active.length}}}
function upsertStudent(s,cohortId){db.prepare(`INSERT INTO records(name,department,student_type,credits,note,group_name,group_contact,political_status,league_branch,phone,email,withdrawn,withdrawal_note,source_total,cohort_id,updated_at) VALUES(?,?,?,0,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(name,department,student_type) DO UPDATE SET note=excluded.note,group_name=excluded.group_name,group_contact=excluded.group_contact,political_status=excluded.political_status,league_branch=excluded.league_branch,phone=excluded.phone,email=excluded.email,withdrawn=excluded.withdrawn,withdrawal_note=excluded.withdrawal_note,source_total=excluded.source_total,cohort_id=excluded.cohort_id,updated_at=CURRENT_TIMESTAMP`).run(s.name,s.department,s.studentType,s.note,s.groupName,s.groupContact,s.politicalStatus,s.leagueBranch,s.phone,s.email,s.withdrawn,s.withdrawalNote,s.sourceTotal,cohortId);return db.prepare("SELECT id FROM records WHERE name=? AND department=? AND student_type=? AND cohort_id=?").get(s.name,s.department,s.studentType,cohortId).id}
function workbookBuffer(cohortId,template=false){
 const wb=XLSX.utils.book_new(),courses=template?[{id:0,name:"必修课程1",category:"required",credits:2},{id:-1,name:"必修课程2",category:"required",credits:2},{id:-2,name:"必修课程3",category:"required",credits:2},{id:-3,name:"必修课程4",category:"required",credits:2},{id:-4,name:"选修课程1",category:"elective",credits:3}]:courseRows(cohortId).filter(c=>c.active),headers=["组别","序号","小组联络员","姓名","政治面貌","院系","所属团支部","手机","电子邮箱",...courses.map(c=>c.name)];
 for(const type of ["undergraduate","graduate"]){const rows=[headers];if(!template){const students=db.prepare("SELECT * FROM records WHERE cohort_id=? AND student_type=? ORDER BY group_name,name").all(cohortId,type),attendance=db.prepare("SELECT student_id,course_id,status,source_mark FROM attendance").all(),map=new Map(attendance.map(a=>[`${a.student_id}:${a.course_id}`,a]));students.forEach((s,i)=>rows.push([s.group_name,i+1,s.group_contact,s.name+(s.withdrawn?`（${s.withdrawal_note||"退出"}）`:""),s.political_status,s.department,s.league_branch,s.phone,s.email,...courses.map(c=>{const a=map.get(`${s.id}:${c.id}`);return a?.status==="special"?(a.source_mark||"2 2/3"):a?.status==="makeup"?2:a?.status==="attended"?1:""})]))}const ws=XLSX.utils.aoa_to_sheet(rows);ws["!cols"]=headers.map((_,i)=>({wch:i===3||i>=9?22:16}));XLSX.utils.book_append_sheet(wb,ws,type==="undergraduate"?"本科组":"硕博组")}
 const courseSheet=XLSX.utils.aoa_to_sheet([["课程名称","课程类型","标准学分","排序"],...courses.map((c,i)=>[c.name,c.category==="required"?"必修":"选修",c.credits,c.sortOrder??i+1])]);XLSX.utils.book_append_sheet(wb,courseSheet,"课程设置");
 if(!template){const t=thresholds(cohortId),students=studentRows(cohortId).map(r=>({...r,completed:!r.withdrawn&&r.totalCredits>=t[r.studentType]&&r.requiredCredits>=t.required})),summary=XLSX.utils.aoa_to_sheet([["姓名","院系","学员类型","组别","总学分","必修学分","是否结业","是否退出","退出备注"],...students.map(r=>[r.name,r.department,r.studentType==="undergraduate"?"本科生":"硕博生",r.groupName,r.totalCredits,r.requiredCredits,r.completed?"是":"否",r.withdrawn?"是":"否",r.withdrawalNote])]),settings=XLSX.utils.aoa_to_sheet([["本科生结业学分","硕博生结业学分","必修课结业学分"],[t.undergraduate,t.graduate,t.required]]);XLSX.utils.book_append_sheet(wb,summary,"学员汇总");XLSX.utils.book_append_sheet(wb,settings,"结业设置")}
 return XLSX.write(wb,{type:"buffer",bookType:"xlsx"})}

async function api(req,res,url){try{
if(req.method==="GET"&&url.pathname==="/api/meta"){const cohorts=db.prepare("SELECT id,name FROM cohorts WHERE active=1 ORDER BY id DESC").all(),cohortId=Number(url.searchParams.get("cohortId"));const departments=cohortId?db.prepare("SELECT DISTINCT department FROM records WHERE cohort_id=? ORDER BY department COLLATE NOCASE").all(cohortId).map(r=>r.department):[];return json(res,200,{cohorts,departments,thresholds:cohortId?thresholds(cohortId):null})}
if(req.method==="POST"&&url.pathname==="/api/query"){const d=await body(req),name=str(d.name,40),department=str(d.department,80),studentType=validType(d.studentType),cohortId=Number(d.cohortId);if(!name||!department||!studentType||!cohortId)return json(res,400,{error:"请选择培训班，并填写姓名、院系和学员类型"});const student=db.prepare(`SELECT r.id,r.name,r.department,r.student_type AS studentType,r.withdrawn,${creditExpr} AS totalCredits,${requiredExpr} AS requiredCredits FROM records r WHERE r.name=? AND r.department=? AND r.student_type=? AND r.cohort_id=?`).get(name,department,studentType,cohortId);if(!student)return json(res,404,{error:"未查到对应记录，请核对培训班、姓名、院系和学员类型"});const t=thresholds(cohortId),completed=!student.withdrawn&&student.totalCredits>=t[student.studentType]&&student.requiredCredits>=t.required,courses=db.prepare("SELECT c.name,c.category,COALESCE(a.credit_override,c.credits) AS credits,a.status FROM attendance a JOIN courses c ON c.id=a.course_id WHERE a.student_id=? AND c.active=1 ORDER BY c.sort_order,c.id").all(student.id);return json(res,200,{name:student.name,department:student.department,totalCredits:student.totalCredits,requiredCredits:student.requiredCredits,completed,withdrawn:!!student.withdrawn,thresholds:t,courses})}
if(req.method==="POST"&&url.pathname==="/api/admin/login"){const d=await body(req),account=db.prepare("SELECT * FROM admin_accounts WHERE username=? AND active=1").get(str(d.username,60));if(!account||!passwordMatches(d.password||"",account.password_hash))return json(res,401,{error:"账号或密码不正确"});const cohortId=account.role==="liaison"?Number(account.cohort_id):Number(d.cohortId),cohort=db.prepare("SELECT id,name FROM cohorts WHERE id=? AND active=1").get(cohortId);if(!cohort)return json(res,400,{error:"请选择有效的培训班"});const t=randomBytes(32).toString("base64url"),session={expires:Date.now()+SESSION_MS,cohortId,user:account};sessions.set(t,session);return json(res,200,{ok:true,dashboard:dashboard(session)},{"Set-Cookie":`pku_admin=${t}; HttpOnly; SameSite=Lax; Path=/; Max-Age=43200${secureCookie}`})}
if(req.method==="POST"&&url.pathname==="/api/admin/logout"){sessions.delete(token(req));return json(res,200,{ok:true},{"Set-Cookie":`pku_admin=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${secureCookie}`})}
if(req.method==="GET"&&url.pathname==="/api/admin/dashboard"){const s=requireAdmin(req,res);if(!s)return;return json(res,200,dashboard(s))}
if(req.method==="POST"&&url.pathname==="/api/admin/settings"){const s=requireWrite(req,res);if(!s)return;const d=await body(req),u=Number(d.undergraduate),g=Number(d.graduate),required=Number(d.required);if(![u,g,required].every(v=>Number.isFinite(v)&&v>=0&&v<=10000))return json(res,400,{error:"结业学分无效"});db.prepare("INSERT INTO cohort_settings(cohort_id,threshold_undergraduate,threshold_graduate,threshold_required) VALUES(?,?,?,?) ON CONFLICT(cohort_id) DO UPDATE SET threshold_undergraduate=excluded.threshold_undergraduate,threshold_graduate=excluded.threshold_graduate,threshold_required=excluded.threshold_required").run(s.cohortId,u,g,required);return json(res,200,{ok:true})}
if(req.method==="POST"&&url.pathname==="/api/admin/cohorts"){const session=requireWrite(req,res);if(!session)return;const d=await body(req),name=str(d.name,100),id=Number(d.id);if(!name)return json(res,400,{error:"培训班名称不能为空"});if(id)db.prepare("UPDATE cohorts SET name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(name,id);else{const result=db.prepare("INSERT INTO cohorts(name) VALUES(?)").run(name);db.prepare("INSERT INTO cohort_settings(cohort_id) VALUES(?)").run(Number(result.lastInsertRowid))}return json(res,200,{ok:true})}
if(req.method==="POST"&&url.pathname==="/api/admin/students"){const session=requireWrite(req,res);if(!session)return;const s=cleanStudent(await body(req)),id=upsertStudent(s,session.cohortId);return json(res,200,{ok:true,id})}
const studentMatch=url.pathname.match(/^\/api\/admin\/students\/(\d+)$/);
if(req.method==="GET"&&studentMatch){const session=requireAdmin(req,res);if(!session)return;const cohortId=session.cohortId,id=Number(studentMatch[1]),group=session.user.role==="liaison"?session.user.group_name:"",student=studentRows(cohortId,group).find(r=>r.id===id);if(!student)return json(res,404,{error:"学员不存在或不在账号管理范围内"});const attendance=db.prepare("SELECT c.id AS courseId,c.name,c.category,c.credits,a.status,a.source_mark AS sourceMark,a.credit_override AS creditOverride FROM courses c LEFT JOIN attendance a ON a.course_id=c.id AND a.student_id=? WHERE c.active=1 AND c.cohort_id=? ORDER BY c.sort_order,c.id").all(id,cohortId);return json(res,200,{student,attendance})}
if(req.method==="POST"&&url.pathname==="/api/admin/courses"){const session=requireWrite(req,res);if(!session)return;const cohortId=session.cohortId,c=cleanCourse(await body(req));if(c.id)db.prepare("UPDATE courses SET name=?,category=?,credits=?,sort_order=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND cohort_id=?").run(c.name,c.category,c.credits,c.sortOrder,c.active,c.id,cohortId);else{c.key=`${cohortId}:${c.key}`;db.prepare("INSERT INTO courses(course_key,name,category,credits,sort_order,active,source_header,cohort_id) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(course_key) DO UPDATE SET name=excluded.name,category=excluded.category,credits=excluded.credits,sort_order=excluded.sort_order,active=excluded.active,source_header=excluded.source_header,updated_at=CURRENT_TIMESTAMP").run(c.key,c.name,c.category,c.credits,c.sortOrder,c.active,c.sourceHeader,cohortId)}return json(res,200,{ok:true})}
const courseMatch=url.pathname.match(/^\/api\/admin\/courses\/(\d+)$/);
if(req.method==="DELETE"&&courseMatch){const session=requireWrite(req,res);if(!session)return;db.prepare("UPDATE courses SET active=0,updated_at=CURRENT_TIMESTAMP WHERE id=? AND cohort_id=?").run(Number(courseMatch[1]),session.cohortId);return json(res,200,{ok:true})}
const courseAttendanceMatch=url.pathname.match(/^\/api\/admin\/courses\/(\d+)\/attendance$/);
if(req.method==="GET"&&courseAttendanceMatch){const session=requireAdmin(req,res);if(!session)return;const cohortId=session.cohortId,courseId=Number(courseAttendanceMatch[1]),course=courseRows(cohortId).find(c=>c.id===courseId);if(!course)return json(res,404,{error:"课程不存在"});const group=session.user.role==="liaison"?session.user.group_name:"",where=group?"r.cohort_id=? AND r.group_name=?":"r.cohort_id=?",args=group?[courseId,cohortId,group]:[courseId,cohortId],students=db.prepare(`SELECT r.id,r.name,r.department,r.student_type AS studentType,r.group_name AS groupName,r.withdrawn,a.status,a.source_mark AS sourceMark,a.credit_override AS creditOverride FROM records r LEFT JOIN attendance a ON a.student_id=r.id AND a.course_id=? WHERE ${where} ORDER BY r.withdrawn,r.student_type,r.group_name,r.name`).all(...args);return json(res,200,{course,students})}
if(req.method==="POST"&&courseAttendanceMatch){if(!requireWrite(req,res))return;const courseId=Number(courseAttendanceMatch[1]),d=await body(req);if(!Array.isArray(d.items))return json(res,400,{error:"出勤数据无效"});db.exec("BEGIN");try{const del=db.prepare("DELETE FROM attendance WHERE student_id=? AND course_id=?"),up=db.prepare("INSERT INTO attendance(student_id,course_id,status,source_mark,credit_override,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(student_id,course_id) DO UPDATE SET status=excluded.status,source_mark=excluded.source_mark,credit_override=excluded.credit_override,updated_at=CURRENT_TIMESTAMP");for(const x of d.items){const studentId=Number(x.studentId);if(!studentId)continue;if(!x.status)del.run(studentId,courseId);else if(["attended","makeup","special"].includes(x.status))up.run(studentId,courseId,x.status,"",x.status==="special"?8:null)}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}return json(res,200,{ok:true})}
if(req.method==="POST"&&url.pathname==="/api/admin/attendance"){if(!requireWrite(req,res))return;const d=await body(req),studentId=Number(d.studentId);if(!studentId||!Array.isArray(d.items))return json(res,400,{error:"出勤数据无效"});db.exec("BEGIN");try{const del=db.prepare("DELETE FROM attendance WHERE student_id=? AND course_id=?"),up=db.prepare("INSERT INTO attendance(student_id,course_id,status,source_mark,credit_override,updated_at) VALUES(?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(student_id,course_id) DO UPDATE SET status=excluded.status,source_mark=excluded.source_mark,credit_override=excluded.credit_override,updated_at=CURRENT_TIMESTAMP");for(const x of d.items){const courseId=Number(x.courseId);if(!courseId)continue;if(!x.status)del.run(studentId,courseId);else if(["attended","makeup","special"].includes(x.status)){const override=x.status==="special"?8:null;up.run(studentId,courseId,x.status,str(x.sourceMark,30),override)}}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}return json(res,200,{ok:true})}
if(req.method==="POST"&&url.pathname==="/api/admin/import-full"){const session=requireWrite(req,res);if(!session)return;const cohortId=session.cohortId,d=await body(req);if(!Array.isArray(d.students)||!Array.isArray(d.courses)||!Array.isArray(d.attendance))return json(res,400,{error:"导入数据结构不正确"});if(d.students.length>3000||d.attendance.length>100000)return json(res,400,{error:"导入数据量过大"});db.exec("BEGIN");try{const courseIds=new Map();for(const raw of d.courses){const c=cleanCourse(raw),sourceKey=c.key;c.key=`${cohortId}:${sourceKey}`;db.prepare("INSERT INTO courses(course_key,name,category,credits,sort_order,active,source_header,cohort_id) VALUES(?,?,?,?,?,1,?,?) ON CONFLICT(course_key) DO UPDATE SET name=excluded.name,category=excluded.category,credits=excluded.credits,sort_order=excluded.sort_order,active=1,source_header=excluded.source_header,cohort_id=excluded.cohort_id,updated_at=CURRENT_TIMESTAMP").run(c.key,c.name,c.category,c.credits,c.sortOrder,c.sourceHeader,cohortId);courseIds.set(sourceKey,db.prepare("SELECT id FROM courses WHERE course_key=?").get(c.key).id)}const studentIds=new Map();for(const raw of d.students){const s=cleanStudent(raw),id=upsertStudent(s,cohortId);studentIds.set(raw.importKey,id);db.prepare("DELETE FROM attendance WHERE student_id=?").run(id)}const ins=db.prepare("INSERT INTO attendance(student_id,course_id,status,source_mark,credit_override) VALUES(?,?,?,?,?) ON CONFLICT(student_id,course_id) DO UPDATE SET status=excluded.status,source_mark=excluded.source_mark,credit_override=excluded.credit_override,updated_at=CURRENT_TIMESTAMP");for(const a of d.attendance){const sid=studentIds.get(a.studentKey),cid=courseIds.get(a.courseKey);if(sid&&cid&&["attended","makeup","special"].includes(a.status))ins.run(sid,cid,a.status,str(a.sourceMark,30),a.status==="special"?8:null)}db.exec("COMMIT")}catch(e){db.exec("ROLLBACK");throw e}return json(res,200,{ok:true,students:d.students.length,courses:d.courses.length,attendance:d.attendance.length})}
if(req.method==="GET"&&url.pathname==="/api/admin/template.xlsx"){const s=requireWrite(req,res);if(!s)return;return binary(res,workbookBuffer(s.cohortId,true),"完整导入模板.xlsx")}
if(req.method==="GET"&&url.pathname==="/api/admin/export.xlsx"){const s=requireWrite(req,res);if(!s)return;return binary(res,workbookBuffer(s.cohortId,false),`${db.prepare("SELECT name FROM cohorts WHERE id=?").get(s.cohortId).name}-完整数据.xlsx`)}
if(req.method==="GET"&&url.pathname==="/api/admin/accounts"){if(!requireSuper(req,res))return;const accounts=db.prepare("SELECT a.id,a.username,a.role,a.cohort_id AS cohortId,c.name AS cohortName,a.group_name AS groupName,a.active FROM admin_accounts a LEFT JOIN cohorts c ON c.id=a.cohort_id ORDER BY CASE a.role WHEN 'super' THEN 0 WHEN 'org' THEN 1 ELSE 2 END,a.username").all();return json(res,200,{accounts,cohorts:db.prepare("SELECT id,name FROM cohorts WHERE active=1 ORDER BY id DESC").all()})}
if(req.method==="POST"&&url.pathname==="/api/admin/accounts"){
 const session=requireSuper(req,res);if(!session)return;
 const d=await body(req),id=Number(d.id),username=str(d.username,60),password=String(d.password||""),role=["super","org","liaison"].includes(d.role)?d.role:"",cohortId=role==="liaison"?Number(d.cohortId):null,groupName=role==="liaison"?str(d.groupName,40):"",target=id?db.prepare("SELECT username,role FROM admin_accounts WHERE id=?").get(id):null;
 if(!username||!role||(!id&&!password)||(role==="liaison"&&(!cohortId||!groupName)))return json(res,400,{error:"请完整填写账号、角色及管理范围"});
 if(id&&!target)return json(res,404,{error:"账号不存在"});
 if(role==="super"&&(!target||!["pkuzzb","zhangtongwei"].includes(target.username)))return json(res,403,{error:"最高权限账号仅限指定的两个校团委组织部账号"});
 if(target&&["pkuzzb","zhangtongwei"].includes(target.username)&&(role!=="super"||username!==target.username))return json(res,403,{error:"两个最高权限账号不能改名或降权"});
 if(id){db.prepare("UPDATE admin_accounts SET username=?,role=?,cohort_id=?,group_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(username,role,cohortId,groupName,id);if(password)db.prepare("UPDATE admin_accounts SET password_hash=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(passwordHash(password),id)}else db.prepare("INSERT INTO admin_accounts(username,password_hash,role,cohort_id,group_name) VALUES(?,?,?,?,?)").run(username,passwordHash(password),role,cohortId,groupName);
 return json(res,200,{ok:true})}
const accountMatch=url.pathname.match(/^\/api\/admin\/accounts\/(\d+)$/);
if(req.method==="DELETE"&&accountMatch){const session=requireSuper(req,res);if(!session)return;const id=Number(accountMatch[1]),target=db.prepare("SELECT username FROM admin_accounts WHERE id=?").get(id);if(!target)return json(res,404,{error:"账号不存在"});if(target.username===session.user.username||["pkuzzb","zhangtongwei"].includes(target.username))return json(res,403,{error:"当前账号及两个最高权限账号不能删除"});db.prepare("DELETE FROM admin_accounts WHERE id=?").run(id);return json(res,200,{ok:true})}
return json(res,404,{error:"接口不存在"})}catch(e){console.error(e);return json(res,500,{error:e.message==="请求内容过大"?e.message:"服务器处理失败，请稍后重试"})}}

const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("X-Frame-Options","DENY");res.setHeader("Referrer-Policy","same-origin");if(url.pathname.startsWith("/api/"))return api(req,res,url);const file=url.pathname==="/"?join(ROOT,"public","index.html"):url.pathname==="/vendor/xlsx.js"?join(ROOT,"node_modules","xlsx","dist","xlsx.full.min.js"):join(ROOT,"public",url.pathname.replace(/^\//,""));if(!file.startsWith(join(ROOT,"public"))&&!file.includes(join("node_modules","xlsx","dist"))){res.writeHead(403);return res.end()}if(!existsSync(file)){res.writeHead(404);return res.end("Not found")}const extension=extname(file),noCache=[".html",".js",".css"].includes(extension);res.writeHead(200,{"Content-Type":mime[extension]||"application/octet-stream","Cache-Control":noCache?"no-cache, no-store, must-revalidate":"public, max-age=3600"});let content=readFileSync(file);if(extension===".html")content=Buffer.from(content.toString("utf8").replace('/styles.css','/styles.css?v=3').replace('/app.js','/app.js?v=3'),"utf8");res.end(content)});
const port=Number(process.env.PORT||8787);server.listen(port,"0.0.0.0",()=>console.log(`网站已启动：http://localhost:${port}`));
