import XLSX from "xlsx";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const ROOT=join(dirname(fileURLToPath(import.meta.url)),"..");
const source=process.argv[2];if(!source)throw new Error("缺少 Excel 文件路径");
const canonical=(i,h)=>["1031破冰","1115开班仪式＋第一次实务技能培训","第二次实务技能培训","0517第三次实务技能培训"][i]||String(h||"").replace(/（[^）]*学分[^）]*）/g,"").trim();
const credits=i=>i===0?4:i===1?5:i===2?2:i===3?3:i<=13?2:3;
function parse(wb){const sheets=wb.SheetNames.filter(n=>/本科|硕博/.test(n));let courses=[],students=[],attendance=[];for(const sn of sheets){const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,defval:null,raw:true}),headers=rows[0]||[];let end=9;while(end<headers.length&&headers[end]!=null&&String(headers[end]).trim())end++;const type=/本科/.test(sn)?"undergraduate":"graduate";if(end-9>courses.length)courses=Array.from({length:end-9},(_,i)=>({courseKey:`course_${String(i+1).padStart(2,"0")}`,name:canonical(i,headers[9+i]),category:i<=3?"required":"elective",credits:credits(i),sortOrder:i+1,sourceHeader:String(headers[9+i]||"")}));let group="",contact="";for(let r=1;r<rows.length;r++){const row=rows[r];group=row[0]??group;contact=row[2]??contact;let name=String(row[3]??"").trim();if(!name)continue;const tail=row.slice(end).filter(v=>v!==null&&v!=="").map(String).join(" "),withdrawn=/休学|退出|退班/.test(name+" "+tail),withdrawalNote=name.match(/[（(](休学|退出|退班)[）)]/)?.[1]||tail.match(/休学|退出|退班/)?.[0]||"";name=name.replace(/[（(](休学|退出|退班)[）)]/g,"").trim();let sourceTotal=null;for(let c=row.length-1;c>=end;c--)if(typeof row[c]==="number"&&Number.isFinite(row[c])){sourceTotal=row[c];break}const importKey=`${sn}:${r+1}`;students.push({importKey,name,department:String(row[5]??"").trim(),studentType:type,groupName:String(group??"").trim(),groupContact:String(contact??"").trim(),politicalStatus:String(row[4]??"").trim(),leagueBranch:String(row[6]??"").trim(),phone:String(row[7]??"").trim(),email:String(row[8]??"").trim(),withdrawn,withdrawalNote,sourceTotal,note:tail});for(let i=0;i<end-9;i++){const v=row[9+i];if(v==null||v==="")continue;const n=Number(v),status=Math.abs(n-1)<.01?"attended":Math.abs(n-2)<.01?"makeup":"special";attendance.push({studentKey:importKey,courseKey:`course_${String(i+1).padStart(2,"0")}`,status,sourceMark:String(v)})}}}return{students,courses,attendance}}
const payload=parse(XLSX.readFile(source,{cellFormula:true}));
const username=process.env.IMPORT_ADMIN_USERNAME,password=process.env.IMPORT_ADMIN_PASSWORD;if(!username||!password)throw new Error("请设置 IMPORT_ADMIN_USERNAME 和 IMPORT_ADMIN_PASSWORD");
const meta=await(await fetch("http://localhost:8787/api/meta")).json(),cohortId=meta.cohorts[0]?.id;if(!cohortId)throw new Error("没有可用的培训班");
const login=await fetch("http://localhost:8787/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username,password,cohortId})});if(!login.ok)throw new Error("管理员登录失败");const cookie=login.headers.getSetCookie?.()[0]?.split(";")[0]||login.headers.get("set-cookie").split(";")[0];
const res=await fetch("http://localhost:8787/api/admin/import-full",{method:"POST",headers:{"Content-Type":"application/json","Cookie":cookie},body:JSON.stringify(payload)});const result=await res.json();if(!res.ok)throw new Error(result.error||"导入失败");console.log(JSON.stringify({...result,withdrawn:payload.students.filter(s=>s.withdrawn).length,special:payload.attendance.filter(a=>a.status==="special").length}));
